### ISSUE TITLE
Run Time Error while running SparkApplication.scala

### ISSUE THREAD

**Issue by sbklog2017** [knoldus/kafka-streams-scala-examples#1]
I cloned your above project in git, did a sbt compile and sbt package, all went good.

When I try to run the StreamsApplication.scala through Spark-Submit as below, I am getting the error 

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/streams/processor/TopologyBuilder

Please guide how to fix this..

============================================================

spark-submit --class com.knoldus.kafka.examples.StreamApplication --master local[4]  /Users/siva/git/kafka-streams-scala-examples/target/scala-2.12/kafka-streams-scala-examples_2.12-0.1.0-SNAPSHOT.jar

=========================================================

C:\Users\siva\git\kafka-streams-scala-examples>spark-submit --class com.knoldus.kafka.examples.StreamApplication --master local[4]  /Users/siva/git/kafka-streams-scala-examples/target/scala-2.12/kafka-streams-scala-examples_2.12-0.1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/kafka/streams/processor/TopologyBuilder
        at com.knoldus.kafka.examples.StreamApplication.main(StreamApplication.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:775)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.streams.processor.TopologyBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

**Comment by gupta-himanshu** [comment]
@sbklog2017 It looks like you are trying to run `Apache Spark` with `Kafka Streams`. If you run your application via `sbt run`, then it would run fine as application's classpath will contain all the required dependencies. However, if you run your application via `spark-submit` then you have to provide all the dependencies in the classpath (which are not included in the fat jar using `sbt assembly`). So, you have to provide them with `spark-submit` command, like this -

```
spark-submit --conf spark.driver.extraClassPath=/path/to/kafka-streams-0.10.2.1.jar:/path/to/kafka-clients-0.10.2.1.jar --conf spark.executor.extraClassPath=/path/to/kafka-streams-0.10.2.1.jar:/path/to/kafka-clients-0.10.2.1.jar --class com.knoldus.kafka.examples.StreamApplication --master local[4] /Users/siva/git/kafka-streams-scala-examples/target/scala-2.12/kafka-streams-scala-examples_2.12-0.1.0-SNAPSHOT.jar
```
Of course, you have to replace the Kafka JAR(s) version with the one you are using.

I hope this helps!

**Comment by gupta-himanshu** [comment]
@sbklog2017 I hope your issue is resolved since there was no response from your side. So, closing this issue now.
